baseURL = "https://donge.org/"
languageCode = "zh-CN"
title = "东冬の乱记"
theme = "anatole"


[params]
title = "东冬の乱记"
author = "donge.org"
description = "donge.org"
profilePicture = "https://0.gravatar.com/avatar/eea4b40b05d3d09858acb8009b5088a9?d=https%3A%2F%2Fidenticons.github.com%2F4158d3f85d28c6395519d8920d8c8184.png&r=x&s=128"


[menu]

  [[menu.main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[menu.main]]
  name = "Posts"
  weight = 200
  identifier = "posts"
  url = "/posts/"

  [[menu.main]]
  name = "Resume"
  weight = 300
  identifier = "resume"
  url = "/resume/"

  [[menu.main]]
  name = "About"
  weight = 400
  identifier = "about"
  url = "/about/"


