baseURL = "https://donge.org/"
languageCode = "zh-CN"
title = "东冬の乱记"
theme = "anatole"


[params]
title = "东冬の乱记"
author = "donge.org"
description = "donge.org"
profilePicture = "https://avatars.githubusercontent.com/u/1329129?s=400&v=4"

[menu]

  [[menu.main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[menu.main]]
  name = "Posts"
  weight = 200
  identifier = "posts"
  url = "/posts/"

  [[menu.main]]
  name = "Resume"
  weight = 300
  identifier = "resume"
  url = "/resume/"

  [[menu.main]]
  name = "About"
  weight = 400
  identifier = "about"
  url = "/about/"
